version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    shm_size: 2G
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  #validatetitle-module:
  #  image: vinsdocker/eautomationtest1:googletest
  #  container_name: validatetitle
  #  depends_on:
  #    - firefox
  #    - chrome
  #  environment:
  #    - SELENIUM_HUB=selenium-hub
  #  volumes:
  #    - C://temaaap:/usr/share/tag/test-output